### ISSUE TITLE
Auto brightness on Always On Display

### ISSUE THREAD

**Issue by ojosehenrick** [davinci-dev/android_device_xiaomi_davinci#2]
It would be smart to add auto brightness to the AOD to prevent battery drain, just as it happens with miui. In my tests, AOD is draining 2% per hour with that static brightness. Thanks in advance!

**Comment by PIPIPIG233666** [comment]
Done https://github.com/davinci-dev/android_device_xiaomi_sm6150-common/commit/2a06389dd76b0f25bd07bb8f6db2d235c24db117
