### ISSUE TITLE
Camera retraction issues

### ISSUE THREAD

**Issue by ojosehenrick** [davinci-dev/android_device_xiaomi_davinci#4]
I found 2 issues that are different on custom roms and miui:

1- When we switch from one mode to another (for example, in gcam, from front camera to portrait mode or from front camera to settings) the camera, even if it is already out, forces itself out more, which doesn't seem right  and I imagine it could damage it in the long run.

 2- When issue 1 happens, when turning back in the camera does not go completely, getting a little out (it can be pressed in, but isn't right anyway).

Thanks in advance!

**Comment by PIPIPIG233666** [comment]
Tested on Google camera version 7.2.010.276119300
Works fine without the issue u mentioned

**Comment by PIPIPIG233666** [comment]
^-^
