### ISSUE TITLE
Wrong position of the fingerprint on AOD

### ISSUE THREAD

**Issue by ojosehenrick** [davinci-dev/android_device_xiaomi_davinci#5]
I noticed that the position set for the fingerprint sensor is different in AOD and normal lockscreen, it's more to the left than it should be. This may be disruptive to reading the fingerprint as the recognition spot portion is not illuminated. Either way, it is as if it is in the wrong position and should not be difficult to correct.

Thanks in advance!

**Comment by PIPIPIG233666** [comment]
Fixed https://github.com/davinci-dev/android_device_xiaomi_davinci/commit/23a938aa3cf6c18a0e47a9a4641ec10058feb4ab

**Comment by PIPIPIG233666** [comment]
https://review.lineageos.org/c/LineageOS/android_frameworks_base/+/250941
